### PR TITLE
init_arg is now respected by MooseX::Getopt

### PR DESCRIPTION
**Pull request by oalders**
Fixes https://rt.cpan.org/Public/Bug/Display.html?id=97849

### CODE REVIEW

**Comment by autarch** [comment]
@karenetheridge, what do you think? This looks reasonable to me.

**Comment by karenetheridge** [comment]
Nice fix!

My only quibble is that new failing tests ought to be TODO, so as to not make a bisection unhappy, but I think by default `git bisect` uses the LHS of a commit topology so as long as I merge this as --no-ff we should be okay.

I'll release this right now.

Thank you very much, and sorry for the delay in getting to this!

**Comment by oalders** [comment]
Thanks!  I didn't realize that this was causing any tests to fail.  It seemed fine for me locally.

**Comment by karenetheridge** [comment]
> Thanks! I didn't realize that this was causing any tests to fail.

I meant that your first three commits added failing tests -- and then subsequent commits made the tests pass. If a bisect landed on one of those intermediary commits it would get unhappy.

**Comment by oalders** [comment]
Ah, good point.  I'll keep that in mind moving forward.  Thanks for pointing that out.

**Pull request merged**
