### PR TITLE
new_with_options will only pass argv if the class has an argv attribute

### PR DESCRIPTION
**Pull request by pplu**
Hi,

   This is the fix for bug #101938 reported on CPAN RT

Best Regards,

Jose Luis Martinez

### CODE REVIEW

**Comment by karenetheridge** [comment]
This looks great!  ..except we use Test::Fatal in this dist, not Test::Exception :)

**Comment by pplu** [comment]
using Test::Fatal now :)

**Comment by pplu** [comment]
ping? I rewrote the tests to use Test::Fatal. Anything else?

**Comment by karenetheridge** [comment]
These changes do not pass all tests, but I'll fix them.

**Comment by karenetheridge** [comment]
thanks! 0.67 is released.

**Pull request merged**
